# Use a Windows-based JDK image instead of Alpine Linux
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Set working directory
WORKDIR C:/app

# Copy all JAR files in the project to app/libs
COPY */target/*.jar C:/app/libs/

# Ensure script is loaded
COPY run.ps1 C:/app/run.ps1

# Ensure the application runs interactively
ENTRYPOINT ["powershell.exe", "-ExecutionPolicy", "Bypass", "-File", "C:/app/run.ps1"]
